"use client";

import { useMemo, useState } from "react";
import {
  Activity, ArrowDownLeft, ArrowDownToLine, ArrowRight, ArrowUpRight, BadgeCheck,
  Bell, BookOpenCheck, Boxes, ChevronDown, CircleHelp, ClipboardCheck, CreditCard,
  FileBadge, FileCheck2, Fingerprint, Gauge, History, LayoutDashboard, LifeBuoy,
  LockKeyhole, LogOut, Menu, MoreHorizontal, Search, Settings2, ShieldCheck,
  Smartphone, UserCheck, Users, Wallet, X, Zap
} from "lucide-react";

type Service = { id: string; title: string; description: string; category: string; price: number; icon: typeof Fingerprint };
const initialServices: Service[] = [
  { id: "nin-lookup", title: "NIN Verification", description: "Verify a NIN against an authorized source", category: "Verification", price: 350, icon: Fingerprint },
  { id: "phone-lookup", title: "NIN Phone Lookup", description: "Submit an authorized phone association check", category: "Verification", price: 450, icon: Smartphone },
  { id: "bvn-verify", title: "BVN Verification", description: "Validate a Bank Verification Number", category: "Verification", price: 400, icon: ShieldCheck },
  { id: "demographic", title: "Demographic Match", description: "Compare supplied details with an authorized response", category: "Verification", price: 500, icon: UserCheck },
  { id: "nin-slip", title: "NIN Slip Request", description: "Request an eligible NIN slip document", category: "Documents", price: 1200, icon: FileBadge },
  { id: "bvn-slip", title: "BVN Slip Request", description: "Submit an eligible document request", category: "Documents", price: 1000, icon: FileCheck2 },
  { id: "nin-validation", title: "NIN Validation", description: "Submit a validation request for review", category: "Special services", price: 700, icon: ClipboardCheck },
  { id: "ipe-clearance", title: "IPE Clearance", description: "Submit or track an eligible clearance request", category: "Special services", price: 1500, icon: BadgeCheck },
  { id: "nin-modification", title: "NIN Modification", description: "Start an eligible demographic update request", category: "Special services", price: 2000, icon: Settings2 },
];
const nav = [
  { group: "WORKSPACE", items: [{ name: "Overview", icon: LayoutDashboard }, { name: "Identity services", icon: Fingerprint }, { name: "Request history", icon: History }] },
  { group: "FINANCE", items: [{ name: "My wallet", icon: Wallet }, { name: "Transactions", icon: CreditCard }] },
  { group: "MANAGEMENT", items: [{ name: "Agents", icon: Users }, { name: "Service pricing", icon: Settings2 }, { name: "Activity logs", icon: Activity }] },
];
const money = (n: number) => new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", maximumFractionDigits: 0 }).format(n);

export default function Home() {
  const [section, setSection] = useState("Overview");
  const [admin, setAdmin] = useState(false);
  const [mobileNav, setMobileNav] = useState(false);
  const [services, setServices] = useState(initialServices);
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<Service | null>(null);
  const [notice, setNotice] = useState("");
  const [form, setForm] = useState({ nin: "", phone: "", firstName: "", lastName: "", consent: false });
  const [amount, setAmount] = useState("5000");
  const [walletBalance, setWalletBalance] = useState(48500);
  const [agentStatus, setAgentStatus] = useState<Record<string, string>>({ "Chisom Okafor": "Pending", "Ibrahim Musa": "Approved", "Blessing Eze": "Restricted" });
  const filtered = useMemo(() => services.filter(s => (s.title + " " + s.description + " " + s.category).toLowerCase().includes(query.toLowerCase())), [services, query]);
  const flash = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(""), 3500); };
  const openService = (s: Service) => { setSelected(s); setForm({ nin: "", phone: "", firstName: "", lastName: "", consent: false }); setSection("Identity services"); };
  const submitRequest = (e: React.FormEvent) => { e.preventDefault(); if (!form.consent) return flash("Please confirm that you are authorized to submit this request."); if (walletBalance < (selected?.price || 0)) return flash("Insufficient demo wallet balance. Fund your wallet first."); setWalletBalance(v => v - (selected?.price || 0)); setSelected(null); flash("Demo request recorded in this preview. No provider was contacted."); };
  const navTo = (name: string) => { setSection(name); setSelected(null); setMobileNav(false); };
  return <div className="app-shell">
    {mobileNav && <button className="scrim" aria-label="Close navigation" onClick={() => setMobileNav(false)} />}
    <aside className={`sidebar ${mobileNav ? "sidebar-open" : ""}`}>
      <div className="brand"><div className="brand-mark"><Fingerprint size={23}/></div><div><div className="brand-name">EMPIRE <span>IDENTITY</span></div><div className="brand-caption">IDENTITY HUB</div></div><button className="icon-button sidebar-close" onClick={() => setMobileNav(false)} aria-label="Close menu"><X size={18}/></button></div>
      <div className="workspace-switch"><div className="workspace-avatar">{admin ? "SA" : "MY"}</div><div className="workspace-copy"><strong>{admin ? "Super Admin" : "Agent workspace"}</strong><span>{admin ? "Full access preview" : "Agent account"}</span></div><ChevronDown size={15}/></div>
      <nav className="side-nav">{nav.map(group => <div className="nav-group" key={group.group}><div className="nav-label">{group.group}</div>{group.items.filter(item => admin || !["Agents", "Service pricing", "Activity logs"].includes(item.name)).map(item => <button key={item.name} className={`nav-item ${section === item.name ? "active" : ""}`} onClick={() => navTo(item.name)}><item.icon size={17}/><span>{item.name}</span>{item.name === "Request history" && <span className="nav-count">12</span>}</button>)}</div>)}
      </nav>
      <div className="sidebar-bottom"><div className="help-card"><div className="help-icon"><LifeBuoy size={17}/></div><strong>Need a hand?</strong><p>Visit the help centre for account and service support.</p><button onClick={() => flash("Support contact can be configured by the administrator.")}>Get support <ArrowRight size={13}/></button></div><div className="sidebar-user"><div className="avatar avatar-user">{admin ? "SA" : "MY"}</div><div className="user-copy"><strong>{admin ? "System Administrator" : "Mishael Yakubu"}</strong><span>{admin ? "Super administrator" : "Identity agent"}</span></div><button className="icon-button" aria-label="Profile options" onClick={() => flash("Profile settings are a preview in this starter.")}><MoreHorizontal size={18}/></button></div></div>
    </aside>
    <main className="main-area">
      <header className="topbar"><div className="topbar-left"><button className="icon-button mobile-menu" onClick={() => setMobileNav(true)} aria-label="Open navigation"><Menu size={20}/></button><div className="breadcrumb"><span>Workspace</span><span>/</span><strong>{selected ? selected.title : section}</strong></div></div><div className="topbar-actions"><div className="secure-pill"><span className="secure-dot"/><LockKeyhole size={13}/> Demo environment</div><button className="icon-button notification-button" aria-label="Notifications" onClick={() => flash("You're all caught up.")}><Bell size={18}/><i/></button><button className="top-profile" onClick={() => {setAdmin(!admin); setSection("Overview"); setSelected(null); flash(admin ? "Agent preview enabled." : "Super admin preview enabled.");}}><div className="avatar avatar-user">{admin ? "SA" : "MY"}</div><div className="top-profile-copy"><strong>{admin ? "Admin preview" : "Mishael Yakubu"}</strong><small>{admin ? "Super admin" : "Agent account"}</small></div><ChevronDown size={14}/></button></div></header>
      <div className="content-wrap">
        {section === "Overview" && !selected && <><div className="page-heading"><div><div className="eyebrow"><Zap size={13}/> YOUR IDENTITY WORKSPACE</div><h1>Good afternoon{admin ? ", Admin" : ", Mishael"} <span className="wave">✦</span></h1><p>Here’s what’s happening with your workspace today.</p></div><button className="button button-primary" onClick={() => navTo("Identity services")}><Zap size={15}/> New request</button></div>
          <div className="stat-grid"><Stat icon={Wallet} label="Wallet balance" value={money(walletBalance)} trend="Available demo funds" tone="blue" /><Stat icon={ClipboardCheck} label="Total requests" value="1,284" trend="+12.8% this month" tone="green" /><Stat icon={Activity} label="Completed requests" value="1,196" trend="93.1% completion rate" tone="violet" /><Stat icon={Users} label={admin ? "Registered agents" : "Account status"} value={admin ? "248" : "Approved"} trend={admin ? "18 pending review" : "Identity services enabled"} tone="amber" /></div>
          <div className="dashboard-grid"><section className="panel service-panel"><div className="panel-heading"><div><h2>Popular services</h2><p>Start a request in just a few steps</p></div><button className="text-button" onClick={() => navTo("Identity services")}>View all <ArrowRight size={14}/></button></div><div className="popular-grid">{services.slice(0,4).map(s => <ServiceTile key={s.id} service={s} onClick={() => openService(s)}/>)}</div></section>
          <section className="panel wallet-panel"><div className="panel-heading"><div><h2>Wallet overview</h2><p>Your available funds</p></div><div className="round-icon"><Wallet size={17}/></div></div><div className="balance-label">CURRENT BALANCE</div><div className="balance-value">{money(walletBalance)}</div><div className="wallet-foot"><span><span className="secure-dot"/> Ready to use</span><button className="button button-primary button-small" onClick={() => navTo("My wallet")}>Add funds <ArrowRight size={13}/></button></div><div className="wallet-note"><LockKeyhole size={14}/> Wallet actions are demo-only until payments are connected.</div></section>
          <section className="panel activity-panel"><div className="panel-heading"><div><h2>Recent activity</h2><p>Your latest service requests</p></div><button className="text-button" onClick={() => navTo("Request history")}>See history <ArrowRight size={14}/></button></div><ActivityTable /></section>
          <section className="panel security-panel"><div className="security-banner"><div className="security-symbol"><ShieldCheck size={21}/></div><div><h3>Protect your workspace</h3><p>Only process identity requests you are authorized to make, with the data subject’s consent.</p></div></div><div className="security-list"><div><BadgeCheck size={16}/><span>Consent-first request flow</span></div><div><LockKeyhole size={16}/><span>Restricted identity result access</span></div><div><BookOpenCheck size={16}/><span>Auditable request history</span></div></div></section></div>
        </>}
        {section === "Identity services" && <><div className="page-heading"><div><div className="eyebrow"><Fingerprint size={13}/> SERVICE CATALOGUE</div><h1>{selected ? selected.title : "Identity services"}</h1><p>{selected ? selected.description : "Choose an available service to start an authorized request."}</p></div>{selected && <button className="button button-outline" onClick={() => setSelected(null)}>Back to services</button>}</div>
          {selected ? <div className="request-layout"><section className="panel request-panel"><div className="panel-heading"><div><h2>Request details</h2><p>Enter only the information required for your authorized request.</p></div><span className="status status-approved">Secure form</span></div><form onSubmit={submitRequest} className="request-form">{selected.id.includes("phone") ? <Field label="Phone number" value={form.phone} placeholder="e.g. 08012345678" onChange={v => setForm({...form, phone:v})} required /> : <Field label="NIN / reference number" value={form.nin} placeholder="Enter details required by the provider" onChange={v => setForm({...form, nin:v})} required />}{selected.id.includes("demographic") && <div className="field-row"><Field label="First name" value={form.firstName} placeholder="First name" onChange={v=>setForm({...form,firstName:v})} required/><Field label="Last name" value={form.lastName} placeholder="Last name" onChange={v=>setForm({...form,lastName:v})} required/></div>}<label className="consent-check"><input type="checkbox" checked={form.consent} onChange={e=>setForm({...form,consent:e.target.checked})}/><span>I confirm I am authorized to submit this request and have obtained the data subject’s consent where required.</span></label><button className="button button-primary submit-button" type="submit">Submit demo request <ArrowRight size={15}/></button><p className="form-disclaimer"><LockKeyhole size={13}/> Demo only: this form does not retrieve or modify real identity records.</p></form></section><aside className="panel order-panel"><h2>Request summary</h2><div className="summary-service"><div className="service-icon"><selected.icon size={19}/></div><div><strong>{selected.title}</strong><span>{selected.category}</span></div></div><div className="summary-line"><span>Service fee</span><strong>{money(selected.price)}</strong></div><div className="summary-line"><span>Processing</span><strong>Provider-dependent</strong></div><div className="summary-total"><span>Total</span><strong>{money(selected.price)}</strong></div><div className="balance-available"><span>Available wallet balance</span><strong>{money(walletBalance)}</strong></div></aside></div>
          : <><div className="toolbar"><div className="search-box"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search services..." /></div><span className="results-count">{filtered.length} services</span></div><div className="catalog-grid">{filtered.map(s=><ServiceTile key={s.id} service={s} onClick={()=>openService(s)} large/> )}</div></>}
        </>}
        {section === "My wallet" && <><div className="page-heading"><div><div className="eyebrow"><Wallet size={13}/> WALLET & PAYMENTS</div><h1>My wallet</h1><p>Manage your workspace funds and view demo wallet activity.</p></div></div><div className="wallet-page-grid"><section className="panel wallet-hero"><span className="wallet-hero-label"><Wallet size={15}/> AVAILABLE BALANCE</span><div className="wallet-hero-amount">{money(walletBalance)}</div><p>NGN · Nigerian naira</p><div className="wallet-hero-actions"><button className="button button-light" onClick={()=>document.getElementById("fund-amount")?.focus()}><ArrowDownLeft size={15}/> Fund wallet</button><button className="button button-translucent" onClick={()=>flash("Withdrawal feature is not enabled in demo mode.")}><ArrowUpRight size={15}/> Withdraw</button></div></section><section className="panel fund-panel"><h2>Fund wallet</h2><p>Enter an amount to preview the funding flow.</p><label className="field-label" htmlFor="fund-amount">Amount (NGN)</label><div className="amount-input"><span>₦</span><input id="fund-amount" value={amount} onChange={e=>setAmount(e.target.value.replace(/[^0-9]/g,""))} inputMode="numeric"/></div><div className="quick-amounts">{["2000","5000","10000","20000"].map(a=><button className={amount===a?"quick-active":""} key={a} onClick={()=>setAmount(a)}>{money(Number(a))}</button>)}</div><button className="button button-primary full-button" onClick={()=>flash("Payment gateway is not connected. No payment has been initiated.")}>Continue to payment <ArrowRight size={15}/></button><p className="form-disclaimer"><LockKeyhole size={13}/> Real funding requires verified payment webhooks.</p></section></div><section className="panel activity-panel standalone-panel"><div className="panel-heading"><div><h2>Recent transactions</h2><p>Wallet ledger preview</p></div></div><ActivityTable/></section></>}
        {section === "Request history" && <><div className="page-heading"><div><div className="eyebrow"><History size={13}/> REQUEST MANAGEMENT</div><h1>Request history</h1><p>Review request references and demo processing states.</p></div></div><section className="panel activity-panel standalone-panel"><div className="panel-heading"><div><h2>All requests</h2><p>Latest request activity</p></div></div><ActivityTable/></section></>}
        {section === "Transactions" && <><div className="page-heading"><div><div className="eyebrow"><CreditCard size={13}/> FINANCE</div><h1>Transactions</h1><p>Review your wallet transaction activity.</p></div></div><section className="panel activity-panel standalone-panel"><div className="panel-heading"><div><h2>Transaction history</h2><p>Sample ledger entries</p></div></div><ActivityTable/></section></>}
        {section === "Agents" && admin && <><div className="page-heading"><div><div className="eyebrow"><Users size={13}/> AGENT MANAGEMENT</div><h1>Agent accounts</h1><p>Review and manage agent access in this local preview.</p></div></div><section className="panel activity-panel"><div className="panel-heading"><div><h2>Agent approval queue</h2><p>Demo records only</p></div></div><div className="agent-list">{Object.entries(agentStatus).map(([name,status])=><div className="agent-row" key={name}><div className="avatar avatar-user">{name.split(" ").map(x=>x[0]).join("")}</div><div className="agent-copy"><strong>{name}</strong><span>Agent account · Nigeria</span></div><span className={`status ${status==="Approved"?"status-approved":status==="Pending"?"status-pending":"status-restricted"}`}>{status}</span><select aria-label={`Change status for ${name}`} value={status} onChange={e=>setAgentStatus({...agentStatus,[name]:e.target.value})}><option>Pending</option><option>Approved</option><option>Restricted</option></select></div>)}</div></section></>}
        {section === "Service pricing" && admin && <><div className="page-heading"><div><div className="eyebrow"><Settings2 size={13}/> CATALOGUE MANAGEMENT</div><h1>Service pricing</h1><p>Adjust demo prices. Production prices must be validated server-side.</p></div></div><section className="panel pricing-panel"><div className="panel-heading"><div><h2>Service catalogue</h2><p>Prices shown in Nigerian naira</p></div></div>{services.map(s=><div className="price-row" key={s.id}><div className="service-icon"><s.icon size={18}/></div><div className="agent-copy"><strong>{s.title}</strong><span>{s.category}</span></div><label className="price-editor"><span>₦</span><input aria-label={s.title+" price"} type="number" min="0" value={s.price} onChange={e=>setServices(old=>old.map(x=>x.id===s.id?{...x,price:Math.max(0,Number(e.target.value))}:x))}/></label></div>)}</section></>}
        {section === "Activity logs" && admin && <><div className="page-heading"><div><div className="eyebrow"><Activity size={13}/> SECURITY & AUDIT</div><h1>Activity logs</h1><p>Audit log panel preview for administrator workflows.</p></div></div><section className="panel empty-state"><div className="empty-icon"><ShieldCheck size={24}/></div><h2>No live audit data connected</h2><p>Connect protected server-side audit logging before production use. This panel intentionally shows no real customer records.</p></section></>}
        {!["Overview","Identity services","My wallet","Request history","Transactions","Agents","Service pricing","Activity logs"].includes(section) && <section className="panel empty-state"><div className="empty-icon"><Boxes size={24}/></div><h2>{section}</h2><p>This section is a starter preview. Connect it to your approved data sources to enable production workflows.</p><button className="button button-primary" onClick={()=>navTo("Overview")}>Back to overview</button></section>}
      </div><footer className="footer"><span>© 2026 Empire Identity Hub</span><span><ShieldCheck size={13}/> Privacy-first workspace <span className="footer-dot">·</span> Built for authorized use</span></footer>
    </main>
    {notice && <div role="status" className="toast"><div className="toast-check"><BadgeCheck size={17}/></div><span>{notice}</span><button aria-label="Dismiss notification" onClick={()=>setNotice("")}><X size={15}/></button></div>}
  </div>;
}

function Stat({icon:Icon,label,value,trend,tone}:{icon:typeof Wallet;label:string;value:string;trend:string;tone:string}) { return <div className="stat-card"><div className="stat-top"><span>{label}</span><div className={`stat-icon ${tone}`}><Icon size={17}/></div></div><div className="stat-value">{value}</div><div className="stat-trend">{trend}</div></div>; }
function ServiceTile({service:s,onClick,large=false}:{service:Service;onClick:()=>void;large?:boolean}) { return <button className={`service-tile ${large?"service-tile-large":""}`} onClick={onClick}><div className="service-tile-top"><div className="service-icon"><s.icon size={19}/></div><span className="service-arrow"><ArrowUpRight size={15}/></span></div><strong>{s.title}</strong><p>{s.description}</p><div className="service-tile-bottom"><span className="category-tag">{s.category}</span><strong>{money(s.price)}</strong></div></button>; }
function Field({label,value,placeholder,onChange,required=false}:{label:string;value:string;placeholder:string;onChange:(v:string)=>void;required?:boolean}) { return <label className="field"><span className="field-label">{label}{required?" *":""}</span><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} required={required} autoComplete="off"/></label>; }
function ActivityTable() { const rows=[["NIN Verification","EH-28491","Today, 2:41 PM","Completed","₦350"],["NIN Slip Request","EH-28490","Today, 1:18 PM","Processing","₦1,200"],["BVN Verification","EH-28489","Yesterday","Completed","₦400"],["Demographic Match","EH-28488","Yesterday","Completed","₦500"]]; return <div className="table-scroll"><table className="activity-table"><thead><tr><th>Service</th><th>Reference</th><th>Date</th><th>Status</th><th className="align-right">Amount</th></tr></thead><tbody>{rows.map(r=><tr key={r[1]}><td><strong>{r[0]}</strong></td><td className="ref-cell">{r[1]}</td><td>{r[2]}</td><td><span className={`status ${r[3]==="Completed"?"status-approved":"status-pending"}`}>{r[3]}</span></td><td className="align-right amount-cell">{r[4]}</td></tr>)}</tbody></table></div>; }
